[theme]
primaryColor = "#1976d2"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fa"
textColor = "#212121"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false
